services:
  - type: web
    name: smart-media-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python smart_media_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: PORT
        value: 10000
